buildscript {
    repositories { mavenCentral() }
    dependencies {
        classpath 'org.flywaydb:flyway-database-postgresql:11.20.3'
    }
}

plugins {
    id 'org.springframework.boot' version '4.1.1'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'java'
    id 'checkstyle'
    id 'org.flywaydb.flyway' version '11.20.3'
    id 'jacoco'
}

group = 'com.mgl'
version = '1.0.0'
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:4.1.0'
    implementation project(':accounts-shared-library')

    compileOnly 'org.projectlombok:lombok:1.18.48'
    runtimeOnly 'org.postgresql:postgresql'

    annotationProcessor 'org.projectlombok:lombok:1.18.48'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.48'

    testImplementation 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'io.github.benas:random-beans:3.7.0'

}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

checkstyle {
    toolVersion = '8.45.1'
    ignoreFailures = false
    maxWarnings = 0
}

tasks.register('checkstyle') {
    dependsOn tasks.checkstyleMain
    dependsOn tasks.checkstyleTest
}

tasks.getByName('checkstyle').outputs.upToDateWhen { false }

tasks.register('release') {
    dependsOn tasks.checkstyle
    dependsOn tasks.test
    dependsOn tasks.build
    finalizedBy 'copyJar'
}

tasks.register('copyJar', Copy) {
    from "$buildDir/libs/accounts-service-1.0.0.jar"
    into layout.projectDirectory.dir('../build')
}

tasks.getByName('copyJar').outputs.upToDateWhen { false }

flyway {
    url = System.getenv('FLYWAY_URL')
    user = System.getenv('FLYWAY_USER')
    password = System.getenv('FLYWAY_PASSWORD')

    schemas = ['accountsdb']
}

jacoco {
    toolVersion = '0.8.14'
    reportsDirectory.set(file("$buildDir/jacoco"))
}

test.outputs.upToDateWhen { false }
jacocoTestReport.outputs.upToDateWhen { false }

jacocoTestCoverageVerification {
    violationRules {
        rule {
            limit {
                minimum = 0.9
            }
        }
    }
}

jacocoTestReport {
    dependsOn test
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: [
                    '**/models/**',
                    '**/exceptions/**',
                    '**/dto/**',
                    '**/dao/entities/**',
                    '**/spring/**',
                    '**/accountsservice/AccountsServiceApplication*'
            ])
        }))
    }
}